name: microbo_reputation_app
description: Microbo Reputation App
publish_to: 'none'

version: 1.0.2+6

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.6
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/microbo.png
    - assets/ic_launcher.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/ic_launcher.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/ic_launcher.png"